name: deploy
on:
  push:
    branches: [ master ]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name:  Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish ./RestaurantAIP/RestaurantAPI.csproj -c Release -o ${{ env.DOTNET_ROOT }}/api
  

    

