name: CI
on:
  push:
    branches: [ master, WorkInProgres ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.4.2
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore 
      - name: build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test
